# This is a config for E2B sandbox template.
# You can use template ID (eidap40je5tsojry7dpn) or template name (moodpo-vibe-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("moodpo-vibe-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("moodpo-vibe-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('moodpo-vibe-nextjs-test')

team_id = "5878acca-0e15-4c03-896e-c8a8abbf336a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "moodpo-vibe-nextjs-test"
template_id = "eidap40je5tsojry7dpn"
